### ISSUE TITLE
use_conn_size_analyzer and size or orig/resp_bytes is not accurate for PCR

### ISSUE THREAD

**Issue by CyberTaoFlow** [pmphry/netbase#1]
Hello, 

Great project.  I would like to communicate a known issue with using orig$bytes/resp$bytes or the use_conn_size_analyzer for tracking tx/rx.    The issue is that for TCP these use sequence numbers to calculate the metric.  For long or large connections the TCP seq can wrap which will lead to unreliable results:

From https://docs.zeek.org/en/current/scripts/base/protocols/conn/main.zeek.html

>orig_bytes: count&log&optional
>The number of payload bytes the originator sent. For TCP this is taken from sequence numbers and might be inaccurate (e.g., due to large connections).

>resp_bytes: count&log&optional
>The number of payload bytes the responder sent. See orig_bytes.

In my and others testing this has been confirmed to cause ridiculously large flow tx/rx reports.   Instead it is recommended to use orig/resp_ip_bytes which utilize the len header of the ip frame.

>orig_ip_bytes: count&log&optional
>Number of IP level bytes that the originator sent (as seen on the wire, taken from the IP total_length header field). Only set if use_conn_size_analyzer = T.

Using the *_ip_bytes field on our sensors to calculate PCR and comparing that to the PCR calculated on firewall logs reported tx/rx bytes counts has confirmed accuracy for myself.

**Comment by CyberTaoFlow** [comment]
https://bro.bro-ids.narkive.com/jvsTbmvr/traffic-volume-calculation-using-bro-s-connection-log

**Comment by pmphry** [comment]
Thanks for the feedback Psipher.  Good point, this is something I’ve waffled on for a long time.  We use Zeek’s calculated app bytes (orig/resp_bytes) only because they are more consistent with PCR’s definition as a measure of directionality of application data transfer.  There are issues with this, but there are also issues with using IP bytes.  As you pointed out *_ip_bytes fields are readily available and more accurate, but a non-zero *_ip_bytes value doesn't necessarily indicate data transfer.  

To make that determination for a given packet, we need to subtract the IP and transport header lengths from the total IP datagram length.  Then, sum that calculated payload length for the entire connection, taking into account any retransmits (for TCP), and finally store the total at log-time.  This is all doable in Zeek script via the new_packet() event but it's very expensive to handle.  I haven’t actually benchmarked it though, I’m extra curious now, so I might.  Either way, this is probably better done at a lower level, like in Zeek core, I’m not sure, but I suspect there is a reason the developers haven’t gone this route.  Who knows… I might give it a go myself someday.  

I guess alternatively you can approximate the total packet payload length using *_ip_bytes fields by making some assumptions about header lengths - for example, for IPv4 there is a minimum of 20 IP header bytes and 20 transport header bytes.  You’d have to multiply the assumed header length (say 40 bytes) by the number of packets in the connection (for each side), then subtract that from the respective *_ip_bytes value.  This doesn’t seem like a viable option though since, depending on header options, you can be off by up to 80 bytes for an IPv4 packet, more for IPv6.    

Anyway, for netbase, I may go ahead and add a configurable option to use the IP header bytes instead of orig/resp_bytes.  I can see a case for wanting to assume the risk of these other inaccuracies and just working with the unadjusted PCR value.  Do you think that would be useful?

-Adam

**Comment by CyberTaoFlow** [comment]
Yeah your points about the header not actually indicating application data transfer are valid while on the other hand Im not sure how the size calc is done for non TCP sessions that lack seq.  In practice I have found overall using ip-len header to be more accurate than TCP-seq based values as when the seq based values are affected by the wrap issue they end up being  WAY WAY off.

I think providing the option to use either would be very useful!
